### ISSUE TITLE
rounding on panel items

### ISSUE THREAD

**Issue by mybigman** [scourii/.dotfiles#1]
i love the look you got running on xfce well done.

how do you get the color and rounded pills of items on the panel like your SS @ https://i.redd.it/h3ius1dxjld61.jpg

I copied your gtk.css but seems to have no effect whatsover.

thanks

**Comment by mybigman** [comment]
needs whisper plugin installed to work

**Comment by scourii** [comment]
Did it work for you in the end?

**Comment by mybigman** [comment]
yup

**Comment by scourii** [comment]
good, have fun ;)
